#!/usr/bin/env bash
# sheep version: 1.2

source .sheep.d/env

ABSOLUTE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
PROJECT_NAME="$(basename $ABSOLUTE_PATH)"
UUID="$(cat .sheep.d/uuid)"

echo $PROJECT_NAME
echo $ABSOLUTE_PATH

case $(hostname -s) in
	login0*)
		# We are on binac
		qsub -N "${PROJECT_NAME}-ID-$UUID" \
			 -e err.log \
			 -o out.log \
			 -m bae \
			 -M "thomas.rometsch@uni-tuebingen.de" \
			 -l walltime=$HOURS:00:00 \
			 -l nodes=1:ppn=$NCPU \
			 -q $QUEUE \
			 $1
		;;
  	*)
		$PWD/$1 1>out.log 2>err.log &
  		;;
esac
