#!/usr/bin/env bash
# sheep version: 1.2

# BINAC: Change dir
if [[ ${PBS_O_WORKDIR} ]]
then
	cd $PBS_O_WORKDIR
	module add mpi/openmpi/1.10.3-gnu-5.2
	module add numlib/fftw/3.3.5-openmpi-1.10.3-gnu-5.2
	module add numlib/gsl/2.1
fi

source .sheep.d/env

mpirun -n $NCPU fargo setups/$SETUP/in.par
