#!/usr/bin/env python3


import os
import sys

this_dir = os.path.abspath(os.path.dirname(__file__))
bin_dir = os.path.join(this_dir, "bin")
sys.path.append(bin_dir)

from fargocpt import main

main()