#!/usr/bin/env python3
import os

try:
    from fargocpt.run import main
except ImportError:
    import sys
    sys.path.append("../python/")
    from fargocpt.run import main

file_dir = os.path.dirname(os.path.realpath(__file__))

if __name__=="__main__":
    main(exe=file_dir+"/bin/fargocpt_exe")