#!/usr/bin/env bash
# sheep version: 1.2

source $(dirname $0)/env

case $(hostname -s) in
	login0*)
		# We are on binac
		module load devel/cuda/8.0
		qsub -N "$(cat uuid)" \
			 -e err.log \
			 -o out.log \
			 -m bae \
			 -M "thomas.rometsch@uni-tuebingen.de" \
			 -l walltime=20:00:00 \
			 -l nodes=1:ppn=1:gpus=1:exclusive_process \
			 -q $QUEUE \
			 $1
		;;
	cpt-*)
		bsub -o out.log -e err.log -q $QUEUE $PWD/$1
		;;
  	*)
  		;;
esac
